### ISSUE TITLE
data() should be ref-qualified

### ISSUE THREAD

**Issue by PeterSommerlad** [dbj-systems/dbj--nothing-but#1]
otherwise it will leak lvalue references to temporary objects (likewise assignment is doing).

**Comment by DBJDBJ** [comment]
Of course and obvious. Let me fix it and re-test.  Thanks Peter ...

**Comment by DBJDBJ** [comment]
data() 4 variants done. Tests are passing. Let me look into that assignment.

**Comment by DBJDBJ** [comment]
deleted the rvalue ref-qualified assignments. Tests passed OK.

**Comment by DBJDBJ** [comment]
Closing
