### ISSUE TITLE
defining copy and move operations is superfluous 

### ISSUE THREAD

**Issue by PeterSommerlad** [dbj-systems/dbj--nothing-but#3]
Hi,
I think you took my comments much too far. I would stay with what the comment says, (which is now lying :-)

```
			// copying --  moving 
			// just leave it all to compiler
```

and not try to define your own versions, especially since moving for the simple types is just copying, because they are no resource managers.

```

			// to convert or assign from T is allowed
			// to move from T is allowed
			nothing_but(T&& t_) noexcept : val_(std::move(t_)) { }
			type& operator = (T&& new_val_) & noexcept { val_ = std::move(new_val_); return *this; }
```

In addition deleting the non-defined move ones does not make a difference, when the lvalue-ref-qualified version is defined.

```
            // If you suspect that a type of yours is susceptible to accidental 
			// assignment-to-temporary (like our vec is), consider deleting the 
			// rvalue ref-qualified assignments
			type& operator = (T&& new_val_) && noexcept = delete ;
			type& operator = (T const& new_val_) && noexcept = delete ;
```
the following are also superfluous:
```
			//to convert or assign from T is allowed
			// by copying
			nothing_but(T const& t_) noexcept : val_(t_) { }
			type& operator = (T const& new_val_) & noexcept { val_ = new_val_; return *this; }
```

**Comment by DBJDBJ** [comment]
I might dare to vouch for this header is perfectly usable as it is.

The last thing I (ever) wanted is to get involved in the C++ rule of seven, that was the rule of five, that was the rule of three.

"... moving for the simple types is just copying..."

True. Simplicity is important. I might follow the "Hinants Table" and remove the copy/move operations.

That is all my time permitting. 

Many thanks for your involvement, Peter. I will gladly take in your pull requests. Also if you would like to add some more tests, by no means please do so.

**Comment by DBJDBJ** [comment]
Please review the "simple" branch.
