### ISSUE TITLE
branch simple review: needless code

### ISSUE THREAD

**Issue by PeterSommerlad** [dbj-systems/dbj--nothing-but#7]
I find the following problematic:

```
			type& operator=(T const& new_val_) noexcept { val_ = new_val_; return *this; }
			// assignment-to-temporary is banned
			type& operator=(T&& new_val_) && noexcept = delete;
``` 

better would be IMHO to just lvalue-ref qualify the assignment operator. Does this even compile? Because usually one needs to mark either none or all overloads with a ref qualifier

```
			type& operator=(T const& new_val_) & noexcept { val_ = new_val_; return *this; }
``` 

Other superfluous code where compiler does the right thing: (delete it!)

```
			nothing_but() = default;
			~nothing_but() = default;
```

why are these conversions declared at all ? (delete them!)

```
			// (accidental) conversion to X is banned 
			template <typename X> operator X& () = delete;

			// conversion operators are a bad idea
			operator T& () & = delete;
			operator T& () && = delete;
```

Since you assume that T is copyable, you can (instead of deleting the attempt) return by value in the following cases:

```
			T const& data() const&& = delete;
			T& data() && = delete;
```

could become

```
			T  data() const&& { return val_;}
			T  data() && { return val_;}
```

I do not get why you use a C-style cast to T& when the return value is already an lvalue of type T:

```
			T& data()& { return (T&)val_; }
```

better imho: 

```
			T& data()& { return val_; }
```

Furthermore, I would make all member/friend functions constexpr and noexcept, because for arithmetic types copying cannot throw and compile time computation can benefit from strong types.

Regards
Peter.

**Comment by DBJDBJ** [comment]
Well, I know this project is missing CI/CD and a strong set of tests. Thus any contribution in the form of a pull request will be correctly self-evaluated.
