### ISSUE TITLE
Unless C++20 is wanted, comparison should be fully symmetric otherwise defaulted

### ISSUE THREAD

**Issue by PeterSommerlad** [dbj-systems/dbj--nothing-but#8]
Hi,

if you only want to support C++20, then I recomment that you just default operator<=>() it would to the right thing.

Otherwise, I recommend that you specify all comparison operators, someone might expect, especially since you still allow implicit conversion from T, which I think might be a problematic decision.

**Comment by DBJDBJ** [comment]
Hi @PeterSommerlad I read and understand and I have no time right now to dive in and rectify :( Will get back to it at my earliest convenience. 

For now, 

- I can say it is certain I do not want to support only C++20
- Implicit conversion usually I do not support, it might be I decided to have it in for some good reason


Thanks for your involvement
